/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.k1yoshi.FCalendar;

import com.k1yoshi.First.F;
import static com.k1yoshi.First.FString.$FirstString;
import com.k1yoshi.First.Function;
import com.k1yoshi.First.Yoshi;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author cixneo
 */
public class FCalendar extends javax.swing.JPanel {

    /**
     * Creates new form Calendar
     */
    
    private boolean cargaCompleta = false;
    
    private Color fondo_seleccionado;
    private Color texto_seleccionado;
    
    private Color fondo_dia_actual;
    private Color texto_dia_actual;
    
    private Calendar calendario;
    
    private int dia, mes, año;
    private int dia_actual, mes_actual, año_actual;
    
    private String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    
    long tiempo_ini, tiempo_fin, tiempo_transcurrido;
    Calendar calendario_tiempo;
    
    public FCalendar() {
        initComponents();
        setSize(getPreferredSize());
        
        iniciarValores();
        iniciarStilos();
        calendario.set(año, mes, 0);
        mostrarDias(año, mes, 0);
    }
    
    //<editor-fold defaultstate="collapsed" desc="iniciarValores">
    private void iniciarValores()
    {
        calendario = java.util.Calendar.getInstance();
        
        fondo_seleccionado = new Color(12, 12, 12);
        texto_seleccionado = new Color(211, 211, 211);
        
        fondo_dia_actual = Color.red;
        texto_dia_actual = new Color(211, 211, 211);
        
        dia = calendario.get(java.util.Calendar.DATE);
        mes = calendario.get(java.util.Calendar.MONTH);
        año = calendario.get(java.util.Calendar.YEAR);
        
        dia_actual = calendario.get(java.util.Calendar.DATE);
        mes_actual = calendario.get(java.util.Calendar.MONTH);
        año_actual = calendario.get(java.util.Calendar.YEAR);
        for(int i = (año_actual+50); i > 1930 ; i--)
            comboAños.addItem(i);
        comboAños.setSelectedItem(año_actual);
        comboAños.setVisible(false);
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        comboAños = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(211, 211, 211));
        setMaximumSize(new java.awt.Dimension(410, 300));
        setMinimumSize(new java.awt.Dimension(410, 300));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/k1yoshi/FCalendar/Imagenes/atras.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAtrasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAtrasMouseReleased(evt);
            }
        });

        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/k1yoshi/FCalendar/Imagenes/adelante.png"))); // NOI18N
        btnAdelante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdelanteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAdelanteMouseReleased(evt);
            }
        });

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Enero 2014");
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTituloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTituloMouseReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lun");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mar");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mié");
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jue");
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vie");
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sab");
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dom");
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 15));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 15));
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel9.setBackground(new java.awt.Color(33, 33, 33));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(0, 1));

        btn1.setText("p1");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn1.setMaximumSize(new java.awt.Dimension(50, 25));
        btn1.setMinimumSize(new java.awt.Dimension(50, 25));
        btn1.setPreferredSize(new java.awt.Dimension(50, 25));

        btn8.setText("1");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn8.setMaximumSize(new java.awt.Dimension(50, 25));
        btn8.setMinimumSize(new java.awt.Dimension(50, 25));
        btn8.setPreferredSize(new java.awt.Dimension(50, 25));

        btn15.setText("8");
        btn15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn15.setMaximumSize(new java.awt.Dimension(50, 25));
        btn15.setMinimumSize(new java.awt.Dimension(50, 25));
        btn15.setPreferredSize(new java.awt.Dimension(50, 25));

        btn22.setText("15");
        btn22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn22.setMaximumSize(new java.awt.Dimension(50, 25));
        btn22.setMinimumSize(new java.awt.Dimension(50, 25));
        btn22.setPreferredSize(new java.awt.Dimension(50, 25));

        btn29.setText("f1");
        btn29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn29.setMaximumSize(new java.awt.Dimension(50, 25));
        btn29.setMinimumSize(new java.awt.Dimension(50, 25));
        btn29.setPreferredSize(new java.awt.Dimension(50, 25));

        btn36.setText("f8");
        btn36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn36.setMaximumSize(new java.awt.Dimension(50, 25));
        btn36.setMinimumSize(new java.awt.Dimension(50, 25));
        btn36.setPreferredSize(new java.awt.Dimension(50, 25));

        btn23.setText("16");
        btn23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn23.setMaximumSize(new java.awt.Dimension(50, 25));
        btn23.setMinimumSize(new java.awt.Dimension(50, 25));
        btn23.setPreferredSize(new java.awt.Dimension(50, 25));

        btn9.setText("2");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn9.setMaximumSize(new java.awt.Dimension(50, 25));
        btn9.setMinimumSize(new java.awt.Dimension(50, 25));
        btn9.setPreferredSize(new java.awt.Dimension(50, 25));

        btn16.setText("9");
        btn16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn16.setMaximumSize(new java.awt.Dimension(50, 25));
        btn16.setMinimumSize(new java.awt.Dimension(50, 25));
        btn16.setPreferredSize(new java.awt.Dimension(50, 25));

        btn2.setText("p2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn2.setMaximumSize(new java.awt.Dimension(50, 25));
        btn2.setMinimumSize(new java.awt.Dimension(50, 25));
        btn2.setPreferredSize(new java.awt.Dimension(50, 25));

        btn37.setText("f9");
        btn37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn37.setMaximumSize(new java.awt.Dimension(50, 25));
        btn37.setMinimumSize(new java.awt.Dimension(50, 25));
        btn37.setPreferredSize(new java.awt.Dimension(50, 25));

        btn30.setText("f2");
        btn30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn30.setMaximumSize(new java.awt.Dimension(50, 25));
        btn30.setMinimumSize(new java.awt.Dimension(50, 25));
        btn30.setPreferredSize(new java.awt.Dimension(50, 25));

        btn24.setText("17");
        btn24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn24.setMaximumSize(new java.awt.Dimension(50, 25));
        btn24.setMinimumSize(new java.awt.Dimension(50, 25));
        btn24.setPreferredSize(new java.awt.Dimension(50, 25));

        btn10.setText("3");
        btn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn10.setMaximumSize(new java.awt.Dimension(50, 25));
        btn10.setMinimumSize(new java.awt.Dimension(50, 25));
        btn10.setPreferredSize(new java.awt.Dimension(50, 25));

        btn17.setText("10");
        btn17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn17.setMaximumSize(new java.awt.Dimension(50, 25));
        btn17.setMinimumSize(new java.awt.Dimension(50, 25));
        btn17.setPreferredSize(new java.awt.Dimension(50, 25));

        btn3.setText("p3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn3.setMaximumSize(new java.awt.Dimension(50, 25));
        btn3.setMinimumSize(new java.awt.Dimension(50, 25));
        btn3.setPreferredSize(new java.awt.Dimension(50, 25));

        btn38.setText("f10");
        btn38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn38.setMaximumSize(new java.awt.Dimension(50, 25));
        btn38.setMinimumSize(new java.awt.Dimension(50, 25));
        btn38.setPreferredSize(new java.awt.Dimension(50, 25));

        btn31.setText("f3");
        btn31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn31.setMaximumSize(new java.awt.Dimension(50, 25));
        btn31.setMinimumSize(new java.awt.Dimension(50, 25));
        btn31.setPreferredSize(new java.awt.Dimension(50, 25));

        btn25.setText("18");
        btn25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn25.setMaximumSize(new java.awt.Dimension(50, 25));
        btn25.setMinimumSize(new java.awt.Dimension(50, 25));
        btn25.setPreferredSize(new java.awt.Dimension(50, 25));

        btn11.setText("4");
        btn11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn11.setMaximumSize(new java.awt.Dimension(50, 25));
        btn11.setMinimumSize(new java.awt.Dimension(50, 25));
        btn11.setPreferredSize(new java.awt.Dimension(50, 25));

        btn18.setText("11");
        btn18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn18.setMaximumSize(new java.awt.Dimension(50, 25));
        btn18.setMinimumSize(new java.awt.Dimension(50, 25));
        btn18.setPreferredSize(new java.awt.Dimension(50, 25));

        btn4.setText("p4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn4.setMaximumSize(new java.awt.Dimension(50, 25));
        btn4.setMinimumSize(new java.awt.Dimension(50, 25));
        btn4.setPreferredSize(new java.awt.Dimension(50, 25));

        btn39.setText("f11");
        btn39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn39.setMaximumSize(new java.awt.Dimension(50, 25));
        btn39.setMinimumSize(new java.awt.Dimension(50, 25));
        btn39.setPreferredSize(new java.awt.Dimension(50, 25));

        btn32.setText("f4");
        btn32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn32.setMaximumSize(new java.awt.Dimension(50, 25));
        btn32.setMinimumSize(new java.awt.Dimension(50, 25));
        btn32.setPreferredSize(new java.awt.Dimension(50, 25));

        btn26.setText("19");
        btn26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn26.setMaximumSize(new java.awt.Dimension(50, 25));
        btn26.setMinimumSize(new java.awt.Dimension(50, 25));
        btn26.setPreferredSize(new java.awt.Dimension(50, 25));

        btn12.setText("5");
        btn12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn12.setMaximumSize(new java.awt.Dimension(50, 25));
        btn12.setMinimumSize(new java.awt.Dimension(50, 25));
        btn12.setPreferredSize(new java.awt.Dimension(50, 25));

        btn19.setText("12");
        btn19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn19.setMaximumSize(new java.awt.Dimension(50, 25));
        btn19.setMinimumSize(new java.awt.Dimension(50, 25));
        btn19.setPreferredSize(new java.awt.Dimension(50, 25));

        btn5.setText("p5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn5.setMaximumSize(new java.awt.Dimension(50, 25));
        btn5.setMinimumSize(new java.awt.Dimension(50, 25));
        btn5.setPreferredSize(new java.awt.Dimension(50, 25));

        btn40.setText("f12");
        btn40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn40.setMaximumSize(new java.awt.Dimension(50, 25));
        btn40.setMinimumSize(new java.awt.Dimension(50, 25));
        btn40.setPreferredSize(new java.awt.Dimension(50, 25));

        btn33.setText("f5");
        btn33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn33.setMaximumSize(new java.awt.Dimension(50, 25));
        btn33.setMinimumSize(new java.awt.Dimension(50, 25));
        btn33.setPreferredSize(new java.awt.Dimension(50, 25));

        btn27.setText("20");
        btn27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn27.setMaximumSize(new java.awt.Dimension(50, 25));
        btn27.setMinimumSize(new java.awt.Dimension(50, 25));
        btn27.setPreferredSize(new java.awt.Dimension(50, 25));

        btn13.setText("6");
        btn13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn13.setMaximumSize(new java.awt.Dimension(50, 25));
        btn13.setMinimumSize(new java.awt.Dimension(50, 25));
        btn13.setPreferredSize(new java.awt.Dimension(50, 25));

        btn20.setText("13");
        btn20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn20.setMaximumSize(new java.awt.Dimension(50, 25));
        btn20.setMinimumSize(new java.awt.Dimension(50, 25));
        btn20.setPreferredSize(new java.awt.Dimension(50, 25));

        btn6.setText("p6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn6.setMaximumSize(new java.awt.Dimension(50, 25));
        btn6.setMinimumSize(new java.awt.Dimension(50, 25));
        btn6.setPreferredSize(new java.awt.Dimension(50, 25));

        btn41.setText("f13");
        btn41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn41.setMaximumSize(new java.awt.Dimension(50, 25));
        btn41.setMinimumSize(new java.awt.Dimension(50, 25));
        btn41.setPreferredSize(new java.awt.Dimension(50, 25));

        btn34.setText("f6");
        btn34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn34.setMaximumSize(new java.awt.Dimension(50, 25));
        btn34.setMinimumSize(new java.awt.Dimension(50, 25));
        btn34.setPreferredSize(new java.awt.Dimension(50, 25));

        btn28.setText("21");
        btn28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn28.setMaximumSize(new java.awt.Dimension(50, 25));
        btn28.setMinimumSize(new java.awt.Dimension(50, 25));
        btn28.setPreferredSize(new java.awt.Dimension(50, 25));

        btn14.setText("7");
        btn14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn14.setMaximumSize(new java.awt.Dimension(50, 25));
        btn14.setMinimumSize(new java.awt.Dimension(50, 25));
        btn14.setPreferredSize(new java.awt.Dimension(50, 25));

        btn21.setText("14");
        btn21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn21.setMaximumSize(new java.awt.Dimension(50, 25));
        btn21.setMinimumSize(new java.awt.Dimension(50, 25));
        btn21.setPreferredSize(new java.awt.Dimension(50, 25));

        btn7.setText("p7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn7.setMaximumSize(new java.awt.Dimension(50, 25));
        btn7.setMinimumSize(new java.awt.Dimension(50, 25));
        btn7.setPreferredSize(new java.awt.Dimension(50, 25));

        btn42.setText("f14");
        btn42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn42.setMaximumSize(new java.awt.Dimension(50, 25));
        btn42.setMinimumSize(new java.awt.Dimension(50, 25));
        btn42.setPreferredSize(new java.awt.Dimension(50, 25));

        btn35.setText("f7");
        btn35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btn35.setMaximumSize(new java.awt.Dimension(50, 25));
        btn35.setMinimumSize(new java.awt.Dimension(50, 25));
        btn35.setPreferredSize(new java.awt.Dimension(50, 25));

        comboAños.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAñosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(comboAños, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(comboAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMousePressed
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_ini = calendario_tiempo.getTimeInMillis();
    }//GEN-LAST:event_btnAtrasMousePressed

    private void btnAtrasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseReleased
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_fin = calendario_tiempo.getTimeInMillis();
        tiempo_transcurrido = tiempo_fin - tiempo_ini;
        if(tiempo_transcurrido < 300l)
            previousMes();
        else
            previousAño();
    }//GEN-LAST:event_btnAtrasMouseReleased

    private void btnAdelanteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdelanteMousePressed
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_ini = calendario_tiempo.getTimeInMillis();
    }//GEN-LAST:event_btnAdelanteMousePressed

    private void btnAdelanteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdelanteMouseReleased
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_fin = calendario_tiempo.getTimeInMillis();
        tiempo_transcurrido = tiempo_fin - tiempo_ini;
        if(tiempo_transcurrido < 300l)
            nextMes();
        else
            nextAño();
    }//GEN-LAST:event_btnAdelanteMouseReleased

    private void comboAñosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAñosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED && cargaCompleta == true)
        {
            repintarButtons();
            año = Integer.parseInt(comboAños.getSelectedItem().toString());
            calendario.set(año, mes, 0);
            mostrarDias(año, mes, 0);
            comboAños.setVisible(false);
            lblTitulo.setVisible(true);
        }
    }//GEN-LAST:event_comboAñosItemStateChanged

    private void lblTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMousePressed
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_ini = calendario_tiempo.getTimeInMillis();
    }//GEN-LAST:event_lblTituloMousePressed

    private void lblTituloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseReleased
        calendario_tiempo = java.util.Calendar.getInstance();
        tiempo_fin = calendario_tiempo.getTimeInMillis();
        tiempo_transcurrido = tiempo_fin - tiempo_ini;
        if(tiempo_transcurrido > 300l)
        {
            lblTitulo.setVisible(false);
            comboAños.setVisible(true);
        }
    }//GEN-LAST:event_lblTituloMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox comboAños;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    // <editor-fold defaultstate="collapsed" desc="iniciarStilos">
    private void iniciarStilos()
    {
        setBackground(new Color(211, 211, 211));
        btnAtras.setBackground(new Color(0, 0, 0, 0));
        btnAdelante.setBackground(new Color(0, 0, 0, 0));
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton) This;
                if(button.getText().length() > 0)
                {
                    button.putClientProperty("%texto%", button.getText());
                    setStilo(button);
                    seleccionarButton(button);
                }
            }
        });
        btnAdelante.setBorder(BorderFactory.createMatteBorder(
                                    0, 0, 0, 0, new Color(110,110,110)));
        btnAtras.setBorder(BorderFactory.createMatteBorder(
                                    0, 0, 0, 0, new Color(110,110,110)));
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="seleccionarButton">
    private void seleccionarButton(final JButton button)
    {
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtons();
                button.putClientProperty("%seleccionado%", true);
                button.setBackground(fondo_seleccionado);
                button.setForeground(texto_seleccionado);
                dia = Integer.parseInt(button.getText());
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="repintarButtons">
    private void repintarButtons()
    {
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton) This;
                if(button.getText().length() > 0)
                {
                    button.setText(button.getClientProperty("%texto%").toString());
                    resetearStilo(button);
                }
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="limpiarButtons">
    private void limpiarButtons()
    {
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton) This;
                if(button.getText().length() > 0  && button.isOpaque())
                {
                    int dia_act = Integer.parseInt(button.getText());
                    if(dia_act == dia_actual && mes == mes_actual && año == año_actual)
                    {
                        button.setBackground(fondo_dia_actual);
                        button.setForeground(texto_dia_actual);
                    }else{
                        resetearStilo(button);
                    }
                    button.putClientProperty("%seleccionado%", null);
                }
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="mostrarDias">
    private void mostrarDias(int a, int m, int d)
    {
        año = a;
        mes = m;
        dia = d;
        
        lblTitulo.setText(meses[mes]+"  "+ año);
        ocultarBotonesInicio(calendario.get(java.util.Calendar.DAY_OF_WEEK));
        ocultarBotonesFin(calendario.get(java.util.Calendar.DAY_OF_WEEK));
        
        final int inicial = 20 + ((8 - calendario.get(java.util.Calendar.DAY_OF_WEEK)) + 1);
        
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton)This;
                if(button.getText().length() > 0)
                {
                    if(button.isVisible())
                    {
                        if(esNumero(button.getText()))
                        {
                            int dia_act = Integer.parseInt(button.getText());
                            dia_act += (8 - calendario.get(java.util.Calendar.DAY_OF_WEEK));
                            button.setText(dia_act+"");
                            if(dia_act == dia_actual && mes == mes_actual && año == año_actual)
                            {
                                button.setBackground(fondo_dia_actual);
                                button.setForeground(texto_dia_actual);
                            }
                        }else{
                            switch (button.getText().substring(0, 1)) {
                                case "f":
                                    {
                                        int dia_act = Integer.parseInt(button.getText().substring(1,button.getText().length()));
                                        dia_act += inicial;
                                        button.setText(dia_act + "");
                                        if(dia_act == dia_actual && mes == mes_actual && año == año_actual)
                                        {
                                            button.setBackground(fondo_dia_actual);
                                            button.setForeground(texto_dia_actual);
                                        }
                                        break;
                                    }
                                case "p":
                                    {
                                        int dia_act = Integer.parseInt(button.getText().substring(1,button.getText().length()));
                                        dia_act -= (calendario.get(java.util.Calendar.DAY_OF_WEEK) -1);
                                        button.setText(dia_act + "");
                                        if(dia_act == dia_actual && mes == mes_actual && año == año_actual)
                                        {
                                            button.setBackground(fondo_dia_actual);
                                            button.setForeground(texto_dia_actual);
                                        }
                                        break;
                                    }
                            }
                        }
                    }
                }
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="ocultarBotonesInicio">
    private void ocultarBotonesInicio(final int dia_semana)
    {
        final String[] dias_antes = crearArrayButtonsInicio("p",dia_semana);
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton)This;
                if(existe(dias_antes, button.getText()))
                {
                    button.setBackground(new Color(0,0,0,0));
                    button.setForeground(new Color(0,0,0,0));
                    button.setOpaque(false);
                    button.setVisible(true);
                    button.setFocusPainted(false);
                    button.setBorderPainted(false);
                }
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="ocultarBotonesFin">
    private void ocultarBotonesFin(final int dia_semana)
    {
        
        int dias_mes = diasDelMes(mes, año);
        final String[] dias_despues = crearArrayButtonsFin("f",(42 - dias_mes - (dia_semana - 1)));
        $("button").each(new Function<Yoshi>(){
            @Override
            public void internal(Yoshi d) {
                JButton button = (JButton)This;
                if(existe(dias_despues, button.getText()))
                {
                    button.setBackground(new Color(0,0,0,0));
                    button.setForeground(new Color(0,0,0,0));
                    button.setOpaque(false);
                    button.setVisible(true);
                    button.setFocusPainted(false);
                    button.setBorderPainted(false);
                }
            }
        });
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="crearArrayButtonsInicio">
    private String[] crearArrayButtonsInicio(String letra,int dia_semana)
    {
        String[] array = new String[dia_semana - 1];
        for(int i = 1; i < dia_semana; i ++)
        {
            array[i-1] = letra+i;
        }
        return array;
    }
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="crearArrayButtonsFin">
    private String[] crearArrayButtonsFin(String letra,int dia_semana)
    {
        int indice = 0;
        String[] array = new String[dia_semana];
        for(int i = 14; i > (14 - dia_semana); i --)
        {
            array[indice] = letra+(i+"");
            indice ++;
        }
        return array;
    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="setStilo">
    private void setStilo(final JButton boton)
    {
        boton.setBorderPainted(true);
        boton.setContentAreaFilled(false);
        boton.setCursor(Cursor.getPredefinedCursor( Cursor.HAND_CURSOR ));
        boton.setBackground(new Color(211, 211, 211));
        boton.setForeground(new Color(33, 33, 33));
        
        boton.setBorder(BorderFactory.createMatteBorder(
                                    1, 1, 1, 1, new Color(110,110,110)));
        boton.setOpaque(true);
        boton.setVisible(true);
        boton.setFocusPainted(false);
        
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            private Color button_released = new Color(0,0,0);
            private Color texto_released = new Color(255, 255, 255);
            
            private Color button_pressed = new Color(12,12,12);
            private Color texto_pressed = new Color(255,255,255);

         @Override
         public void mouseEntered(MouseEvent evt) {
         }
         @Override
            public void mouseClicked(MouseEvent e) {
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if(boton.getClientProperty("%seleccionado%") == null)
                {
                    //capturamos valores iniciales
                    button_released = boton.getBackground();
                    texto_released = boton.getForeground();
                    //se colocan los nuevos colores
                    boton.setForeground( this.texto_pressed );
                    boton.setBackground( this.button_pressed );
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if(boton.getClientProperty("%seleccionado%") == null)
                {
                    boton.setBackground( this.button_released );
                    boton.setForeground( this.texto_released );
                }
            }
            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="resetearStilos">
    private void resetearStilo(final JButton boton)
    {
        boton.setBorderPainted(true);
        boton.setContentAreaFilled(false);
        boton.setBackground(new Color(211, 211, 211));
        boton.setForeground(new Color(33, 33, 33));
        
        boton.setBorder(BorderFactory.createMatteBorder(
                                    1, 1, 1, 1, new Color(110,110,110)));
        boton.setOpaque(true);
        boton.setVisible(true);
        boton.setFocusPainted(false);
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="$">
    private F<Yoshi> $(String selector)
    {
        return $FirstString(this.getComponents(), selector);
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="diasDelMes">
    private int diasDelMes(int mes, int año)
    {
        switch(mes)
        {
            case 0:  // Enero
            case 2:  // Marzo
            case 4:  // Mayo
            case 6:  // Julio
            case 7:  // Agosto
            case 9:  // Octubre
            case 11: // Diciembre
            return 31;
            case 3:  // Abril
            case 5:  // Junio
            case 8:  // Septiembre
            case 10: // Noviembre
            return 30;
            case 1:  // Febrero
            if ( ((año%100 == 0) && (año%400 == 0)) ||
            ((año%100 != 0) && (año%  4 == 0))   )
            return 29;  // Año Bisiesto
            else
            return 28;
            default: return 0;
        }
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="existe">
    private boolean existe(String[] array, String dato)
    {
        for(String texto : array)
        {
            if(texto.equals(dato))
                return true;
        }
        return false;
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="esNumero">
    private boolean esNumero(String texto)
    {
        for(char caracter : texto.toCharArray())
        {
            if(!Character.isDigit(caracter))
                return false;
        }
        return true;
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="nextMes">
    private void nextMes()
    {
        repintarButtons();
        mes += 1;
        if(mes > 11)
        {
            año++;
            mes = 0;
        }
        calendario.set(año, mes, 0);
        mostrarDias(año, mes, 0);
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="previousMes">
    private void previousMes()
    {
        repintarButtons();
        mes -= 1;
        if(mes < 0)
        {
            año--;
            mes = 11;
        }
        calendario.set(año, mes, 0);
        mostrarDias(año, mes, 0);
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="nextAño">
    private void nextAño()
    {
        repintarButtons();
        año += 1;
        calendario.set(año, mes, 0);
        mostrarDias(año, mes, 0);
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="previousAño">
    private void previousAño()
    {
        repintarButtons();
        año -= 1;
        calendario.set(año, mes, 0);
        mostrarDias(año, mes, 0);
    }
    //</editor-fold>
    
    /**
     * @formato = "d-m-y"
     * */
    //<editor-fold defaultstate="collapsed" desc="getDate">
    public String getDate(String formato)
    {
        if(dia ==0)
            formato = formato.replaceAll("d", dia_actual+"");
        else
            formato = formato.replaceAll("d", dia+"");
        formato = formato.replaceAll("m", (mes+1)+"");
        formato = formato.replaceAll("y", año+"");
        return formato;
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="getDate">
    public String getDate()
    {
        return ((dia==0)?dia_actual:dia)+"/"+(mes+1)+"/"+año;
    }
    //</editor-fold>
}
